FROM golang:1.24 AS builder

WORKDIR /build

COPY . .

RUN go mod download
RUN go build -o ./service_1

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /build/service_1 ./service_1

CMD ["/app/service_1"]