FROM golang:1.24 AS builder

WORKDIR /build

COPY . .

RUN go mod download
RUN go build -o ./service1

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /build/service1 ./service1

CMD ["/app/service1"]