FROM ghcr.io/astral-sh/uv:python3.14-rc-bookworm

ENV UV_COMPILE_BYTECODE=1

WORKDIR /app

COPY pyproject.toml uv.lock ./

# Install dependencies only (not the project itself) to optimize cache usage
RUN uv sync --locked --no-install-project

COPY . .

# Install the project itself
RUN uv sync --locked

CMD ["uv", "run","app.py"]

# FROM ghcr.io/astral-sh/uv:python3.14-rc-bookworm

# # Copy the project into the image
# ADD . /app

# # Sync the project into a new environment, asserting the lockfile is up to date
# WORKDIR /app
# RUN uv sync --locked

# # Presuming there is a my_app command provided by the project
# CMD ["uv", "run", "app.py"]