name: CI Pipeline (Build, Test, and Push Docker Images)

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "readme.md"
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Build Go service
        working-directory: service_1
        run: |
          go mod tidy
          go build -o service_1
      - name: Test Go service
        working-directory: service_1
        run: go test ./...

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: pip install uv
      - name: Sync uv dependencies
        working-directory: service_2
        run: uv sync --locked --no-install-project
      - name: Test Python service
        working-directory: service_2
        run: uv run pytest || true # As we do not have tests yet

  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Echo Docker Hub Username
        run: echo ${{ secrets.DOCKER_USER }}
      - name: Echo GitHub SHA
        run: echo $GITHUB_SHA

      - name: Build and push Go Docker image
        run: |
          docker build -t harshsen/microservice/service1 ./service_1
          docker push harshsen/microservice/service1
      - name: Build and push Python Docker image
        run: |
          docker build -t harshsen/microservice/service2 ./service_2
          docker push harshsen/microservice/service2
      - name: Build and push Nginx Docker image
        run: |
          docker build -t harshsen/microservice/nginx ./nginx
          docker push harshsen/microservice/nginx

      - name: Logout from Docker Hub
        run: docker logout

      - name: End
        run: echo "Docker image pushed to Docker Hub successfully"