name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Test Go service
        working-directory: service_1
        run: go test ./...
      - name: Build Go service
        working-directory: service_1
        run: go build -o service_1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        working-directory: service_2
        run: pip install -r requirements.txt
      - name: Test Flask service
        working-directory: service_2
        run: pytest

      - name: Build Go Docker image
        run: docker build -t service_1 ./service_1
      - name: Build Flask Docker image
        run: docker build -t service_2 ./service_2
